name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
      steps:
        name: hello github action
        run: echo "Hello this is first workflow for github action."
        name: bye github action
        run: echo "Bye github action"
  
