name: Validate workflow
on: workflow_dispatch
jobs:
  file-validate:
    runs-on: "ubuntu-latest"

    steps:
      - name: Get repo code on VM
        uses: actions/checkout@v4
      - name: Validate html file (exist or not)
        run: test -f home.html